// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bhsvgjyawlepaqhgpguf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJoc3Znanlhd2xlcGFxaGdwZ3VmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzNjkwOTQsImV4cCI6MjA2MDk0NTA5NH0.FF0caJe6TB5wWpRW1eIhW5MB12W1_RMe-3sAm-Uxe_w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);